name: Formatting 
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'test'
    steps:
    - uses: actions/checkout@v2
    - name: Clang-Format Check 
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}